# Specific branch context: all deploys from
# this specific branch will inherit these settings.
[context.master.environment] # “master” is a branch name
  REACT_APP_API_URI=http://localhost:3500

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200